### ISSUE TITLE
"LingoSwitch.app" not supported on Intel-based Macs due to architecture compatibility issues.

### ISSUE THREAD

**Issue by zhekch** [mcjkula/lingoswitch#2]
Running the executable throught the terminal returns `bad CPU type in executable: ./LingoSwitch`

**Comment by mcjkula** [comment]
Hi,

are you using an Intel Mac?

**Comment by mcjkula** [comment]
I figured out, I compiled the project only for my current architecture which is ARM, so I have to figure out how I could make it possible to compile for x86_64 as well.

**Comment by mcjkula** [comment]
I need to revisit the code again and look into that, as of now I know of one package dependency I have in this app that doesn't support the x86_64 CPU architecture, so I would probably need to implement that logic myself.

**Comment by Tock96** [comment]
Should I expect an update for computers on intel processors?

**Comment by mcjkula** [comment]
@Tock96 Yes, I am working on an update to support both architectures. I found an API to work with so that I could remove the package dependency.

I will update further in the coming days 🙏🏼

**Comment by mcjkula** [comment]
I released the new version, which should have support for Intel. Please test it out, and if any issues occur feel free to reopen this issue.
